// <auto-generated />
namespace RestaurantRater.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Restaurant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Restaurant));
        
        string IMigrationMetadata.Id
        {
            get { return "202110281638096_Restaurant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
